name: Unity CI

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-unity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android
          - StandaloneLinux64
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup permissions for folders
        run: |
          mkdir -p UnityClient/Assets/Plugins
          sudo chown -R $USER:$USER UnityClient/Assets/Plugins
          mkdir -p UnityClient/build/
          sudo chown -R $USER:$USER UnityClient/build/

      - name: Build and extract shared libraries
        run: |
          docker buildx build \
          --output type=local,dest=UnityClient/Assets/Plugins \
          NativeCV/

      - name: Cache Unity library
        uses: actions/cache@v4
        with:
          path: UnityClient/Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('UnityClient/Assets/**', 'UnityClient/Packages/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: UnityClient
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: UnityClient/build